{"name": "test_login_with_invalid_credentials[2-11]", "status": "passed", "steps": [{"name": "login_attempt_invalid", "status": "passed", "steps": [{"name": "Logging in as: 'standard_user'", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1746361551696, "stop": 1746361552533}], "attachments": [{"name": "login_attempt_invalid", "source": "ef674fcd-7741-4a7f-a0cc-fb2df0bb9f59-attachment.png", "type": "image/png"}], "start": 1746361551696, "stop": 1746361552708}], "parameters": [{"name": "__pytest_repeat_step_number", "value": "1"}], "start": 1746361550088, "stop": 1746361552711, "uuid": "da2c0133-9072-4407-b2a9-bc9326ce6879", "historyId": "ede85da0d5d8cd825478c666301c7ef2", "testCaseId": "168b918d5f30454aee4f2196e4314b1d", "fullName": "tests.test_login_negative.TestLoginNegative#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_negative"}, {"name": "subSuite", "value": "TestLoginNegative"}, {"name": "host", "value": "LAPTOP-J5LLJDIJ"}, {"name": "thread", "value": "28940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_negative"}]}