{"name": "test_login_with_invalid_credentials[6-11]", "status": "passed", "steps": [{"name": "login_attempt_invalid", "status": "passed", "steps": [{"name": "Logging in as: 'standard_user'", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1746361577945, "stop": 1746361578779}], "attachments": [{"name": "login_attempt_invalid", "source": "a6eeb199-7031-48ac-8fc3-ebad99dd2c77-attachment.png", "type": "image/png"}], "start": 1746361577945, "stop": 1746361578957}], "parameters": [{"name": "__pytest_repeat_step_number", "value": "5"}], "start": 1746361576368, "stop": 1746361578961, "uuid": "15d2e502-abc6-4782-b625-4b13154a59a8", "historyId": "20e5453fc28fc60d43955bea618181ba", "testCaseId": "168b918d5f30454aee4f2196e4314b1d", "fullName": "tests.test_login_negative.TestLoginNegative#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_negative"}, {"name": "subSuite", "value": "TestLoginNegative"}, {"name": "host", "value": "LAPTOP-J5LLJDIJ"}, {"name": "thread", "value": "28940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_negative"}]}