{"name": "test_login_with_invalid_credentials[9-11]", "status": "passed", "steps": [{"name": "login_attempt_invalid", "status": "passed", "steps": [{"name": "Logging in as: 'standard_user'", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1746361598329, "stop": 1746361599183}], "attachments": [{"name": "login_attempt_invalid", "source": "b758cfbf-724a-489c-800e-302c78e242f4-attachment.png", "type": "image/png"}], "start": 1746361598329, "stop": 1746361599380}], "parameters": [{"name": "__pytest_repeat_step_number", "value": "8"}], "start": 1746361596567, "stop": 1746361599383, "uuid": "d5838270-2a49-433c-8623-178f0d284ef5", "historyId": "b20862982ca8b2cc36432caf0ea06f19", "testCaseId": "168b918d5f30454aee4f2196e4314b1d", "fullName": "tests.test_login_negative.TestLoginNegative#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_negative"}, {"name": "subSuite", "value": "TestLoginNegative"}, {"name": "host", "value": "LAPTOP-J5LLJDIJ"}, {"name": "thread", "value": "28940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_negative"}]}