{"name": "test_login_with_invalid_credentials[11-11]", "status": "passed", "steps": [{"name": "login_attempt_invalid", "status": "passed", "steps": [{"name": "Logging in as: 'standard_user'", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1746361612477, "stop": 1746361613357}], "attachments": [{"name": "login_attempt_invalid", "source": "dd82940b-a034-4651-971f-f3aa7af26113-attachment.png", "type": "image/png"}], "start": 1746361612476, "stop": 1746361613522}], "parameters": [{"name": "__pytest_repeat_step_number", "value": "10"}], "start": 1746361610806, "stop": 1746361613526, "uuid": "7a177638-c43d-4c10-9eef-4614f726c214", "historyId": "7e2b8ae04af52e79ba8d8aaa278d0cea", "testCaseId": "168b918d5f30454aee4f2196e4314b1d", "fullName": "tests.test_login_negative.TestLoginNegative#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_negative"}, {"name": "subSuite", "value": "TestLoginNegative"}, {"name": "host", "value": "LAPTOP-J5LLJDIJ"}, {"name": "thread", "value": "28940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_negative"}]}