{"name": "test_login_with_invalid_credentials[7-11]", "status": "passed", "steps": [{"name": "login_attempt_invalid", "status": "passed", "steps": [{"name": "Logging in as: 'standard_user'", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1746361584102, "stop": 1746361584970}], "attachments": [{"name": "login_attempt_invalid", "source": "b6d836f2-e580-4baf-ac38-b32e7d606c9f-attachment.png", "type": "image/png"}], "start": 1746361584102, "stop": 1746361585161}], "parameters": [{"name": "__pytest_repeat_step_number", "value": "6"}], "start": 1746361583343, "stop": 1746361585165, "uuid": "a471dafa-b0b8-4548-8ee1-b1da2e8b59f9", "historyId": "268183f3b38769bced15d9b77768136e", "testCaseId": "168b918d5f30454aee4f2196e4314b1d", "fullName": "tests.test_login_negative.TestLoginNegative#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_negative"}, {"name": "subSuite", "value": "TestLoginNegative"}, {"name": "host", "value": "LAPTOP-J5LLJDIJ"}, {"name": "thread", "value": "28940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_negative"}]}