{"name": "test_login_with_invalid_credentials[1-11]", "status": "passed", "steps": [{"name": "login_attempt_invalid", "status": "passed", "steps": [{"name": "Logging in as: 'standard_user'", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1746361544669, "stop": 1746361545552}], "attachments": [{"name": "login_attempt_invalid", "source": "dd688612-3911-4d16-befa-8c787ebc8ff6-attachment.png", "type": "image/png"}], "start": 1746361544669, "stop": 1746361545725}], "parameters": [{"name": "__pytest_repeat_step_number", "value": "0"}], "start": 1746361543037, "stop": 1746361545728, "uuid": "050abc64-155a-49a7-ac31-57d6d1f94dc8", "historyId": "e71bbd0be6e1bbd412fa4886288c8f2c", "testCaseId": "168b918d5f30454aee4f2196e4314b1d", "fullName": "tests.test_login_negative.TestLoginNegative#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_negative"}, {"name": "subSuite", "value": "TestLoginNegative"}, {"name": "host", "value": "LAPTOP-J5LLJDIJ"}, {"name": "thread", "value": "28940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_negative"}]}