{"name": "test_login_with_invalid_credentials[8-11]", "status": "passed", "steps": [{"name": "login_attempt_invalid", "status": "passed", "steps": [{"name": "Logging in as: 'standard_user'", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1746361591142, "stop": 1746361592027}], "attachments": [{"name": "login_attempt_invalid", "source": "9655fd6d-62f2-49c3-9eb1-60427a583574-attachment.png", "type": "image/png"}], "start": 1746361591142, "stop": 1746361592199}], "parameters": [{"name": "__pytest_repeat_step_number", "value": "7"}], "start": 1746361589513, "stop": 1746361592202, "uuid": "9a9c20ed-ddf8-4df6-bbe7-28176797511b", "historyId": "1379189b4303860a49101632eef10099", "testCaseId": "168b918d5f30454aee4f2196e4314b1d", "fullName": "tests.test_login_negative.TestLoginNegative#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_negative"}, {"name": "subSuite", "value": "TestLoginNegative"}, {"name": "host", "value": "LAPTOP-J5LLJDIJ"}, {"name": "thread", "value": "28940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_negative"}]}