{"name": "test_login_with_invalid_credentials[5-11]", "status": "passed", "steps": [{"name": "login_attempt_invalid", "status": "passed", "steps": [{"name": "Logging in as: 'standard_user'", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1746361570905, "stop": 1746361571778}], "attachments": [{"name": "login_attempt_invalid", "source": "f9e08d8c-4233-4f9a-8cbc-e7106fd1c153-attachment.png", "type": "image/png"}], "start": 1746361570905, "stop": 1746361571953}], "parameters": [{"name": "__pytest_repeat_step_number", "value": "4"}], "start": 1746361569702, "stop": 1746361571957, "uuid": "6eee33c8-323f-438b-ab91-5fb7999988a5", "historyId": "1628e982cd6cd7dd39555dab66c2be11", "testCaseId": "168b918d5f30454aee4f2196e4314b1d", "fullName": "tests.test_login_negative.TestLoginNegative#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_negative"}, {"name": "subSuite", "value": "TestLoginNegative"}, {"name": "host", "value": "LAPTOP-J5LLJDIJ"}, {"name": "thread", "value": "28940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_negative"}]}