{"name": "test_login_with_invalid_credentials[3-11]", "status": "passed", "steps": [{"name": "login_attempt_invalid", "status": "passed", "steps": [{"name": "Logging in as: 'standard_user'", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1746361557839, "stop": 1746361558726}], "attachments": [{"name": "login_attempt_invalid", "source": "f91892f0-41da-4a70-8f7a-1fbd6114b93d-attachment.png", "type": "image/png"}], "start": 1746361557839, "stop": 1746361558899}], "parameters": [{"name": "__pytest_repeat_step_number", "value": "2"}], "start": 1746361557088, "stop": 1746361558903, "uuid": "ab46b2f8-ba69-4366-9fc5-18e0410a6aee", "historyId": "35b86a847c5c0349e4452ef52103a633", "testCaseId": "168b918d5f30454aee4f2196e4314b1d", "fullName": "tests.test_login_negative.TestLoginNegative#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_negative"}, {"name": "subSuite", "value": "TestLoginNegative"}, {"name": "host", "value": "LAPTOP-J5LLJDIJ"}, {"name": "thread", "value": "28940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_negative"}]}