{"name": "test_login_with_invalid_credentials[10-11]", "status": "passed", "steps": [{"name": "login_attempt_invalid", "status": "passed", "steps": [{"name": "Logging in as: 'standard_user'", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1746361605387, "stop": 1746361606252}], "attachments": [{"name": "login_attempt_invalid", "source": "eef2a08e-bda8-44be-ae78-2bc6536129c4-attachment.png", "type": "image/png"}], "start": 1746361605387, "stop": 1746361606428}], "parameters": [{"name": "__pytest_repeat_step_number", "value": "9"}], "start": 1746361603772, "stop": 1746361606431, "uuid": "a3321407-6162-419e-be74-9ec77682e4c1", "historyId": "082c4340f79eedd85a724b830daf5599", "testCaseId": "168b918d5f30454aee4f2196e4314b1d", "fullName": "tests.test_login_negative.TestLoginNegative#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_negative"}, {"name": "subSuite", "value": "TestLoginNegative"}, {"name": "host", "value": "LAPTOP-J5LLJDIJ"}, {"name": "thread", "value": "28940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_negative"}]}