{"name": "test_login_with_invalid_credentials[4-11]", "status": "passed", "steps": [{"name": "login_attempt_invalid", "status": "passed", "steps": [{"name": "Logging in as: 'standard_user'", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'wrong_password'"}], "start": 1746361564933, "stop": 1746361565784}], "attachments": [{"name": "login_attempt_invalid", "source": "ce35a6d8-183f-4813-860f-ff74cfc617a5-attachment.png", "type": "image/png"}], "start": 1746361564933, "stop": 1746361565957}], "parameters": [{"name": "__pytest_repeat_step_number", "value": "3"}], "start": 1746361563292, "stop": 1746361565960, "uuid": "5e78bf9b-f852-47ec-8014-2a7714940d48", "historyId": "9762238bfe44f5268a466f28076553ab", "testCaseId": "168b918d5f30454aee4f2196e4314b1d", "fullName": "tests.test_login_negative.TestLoginNegative#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_negative"}, {"name": "subSuite", "value": "TestLoginNegative"}, {"name": "host", "value": "LAPTOP-J5LLJDIJ"}, {"name": "thread", "value": "28940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_negative"}]}